extends Node


var template = { 
	"name" : "name",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#---------Misc Items----------------

var no_weapon = {
	"name" : "no weapon",
	"weapon_tags": [],
	"range_tags": ["close", "hand"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : null,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

var spellbook = { 
	"name" : "spellbook",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : null,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#TODO: make unseen servant an npc instead of an item in the future
var unseen_servant = { 
	"name" : "unseen servant",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : null,
	"weight": -3,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#---------Ranged Weapons----------------
var crossbow = { 
	"name" : "crossbow",
	"weapon_tags": ["+1 damage", "reload"],
	"range_tags": ["near"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 35,
	"weight": 3,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var fine_bow = { 
	"name" : "fine bow",
	"weapon_tags": [],
	"range_tags": ["near", "far"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 60,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var hunters_bow = { 
	"name" : "hunters bow",
	"weapon_tags": [],
	"range_tags": ["near", "far"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 100,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var ragged_bow = { 
	"name" : "ragged bow",
	"weapon_tags": [],
	"range_tags": ["near"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var bundle_of_arrows = { 
	"name" : "bundle of arrows",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1,
	"weight": 1,
	"uses": 3,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var elven_arrows = { 
	"name" : "elven arrows",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 20,
	"weight": 1,
	"uses": 4,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#---------Melee Weapons----------------
var club = { 
	"name" : "club",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var dagger = { 
	"name" : "dagger",
	"weapon_tags": [],
	"range_tags": ["hand"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 2,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var dueling_rapier = { 
	"name" : "dueling rapier",
	"weapon_tags": ["+1 piercing", "precise"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var halberd = { 
	"name" : "halberd",
	"weapon_tags": ["+1 damage"],
	"range_tags": ["reach"],
	"general_tags": ["2-handed"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 9,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var long_sword = { 
	"name" : "long sword",
	"weapon_tags": ["+1 damage"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var battle_axe = { 
	"name" : "battle axe",
	"weapon_tags": ["+1 damage"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var flail = { 
	"name" : "flail",
	"weapon_tags": ["+1 damage"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var rapier = { 
	"name" : "rapier",
	"weapon_tags": ["precise"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 25,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var short_sword = { 
	"name" : "short sword",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 8,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var axe = { 
	"name" : "axe",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 8,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var warhammer = { 
	"name" : "warhammer",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 8,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var mace = { 
	"name" : "mace",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 8,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var spear = { 
	"name" : "spear",
	"weapon_tags": ["thrown"],
	"range_tags": ["reach", "near"], # near when thrown
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 5,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var staff = { 
	"name" : "staff",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": ["2-handed"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var throwing_dagger = { 
	"name" : "throwing dagger",
	"weapon_tags": ["thrown"],
	"range_tags": ["near"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": true,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#---------Armor----------------
var leather_armor = { 
	"name" : "leather armor",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["worn"],
	"armor_tags": ["1 armor"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var plate_armor = { 
	"name" : "plate armor",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["worn"],
	"armor_tags": ["3 armor", "clumsy"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 350,
	"weight": 4,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var scale_mail = { 
	"name" : "scale mail",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["worn"],
	"armor_tags": ["2 armor", "clumsy"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50,
	"weight": 3,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var shield = { 
	"name" : "shield",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": ["+1 armor"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#---------Gear----------------
var adventuring_gear = { 
	"name" : "adventuring gear",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 20,
	"weight": 1,
	"uses": 5,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var antitoxin = { 
	"name" : "antitoxin",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var bag_of_books = { 
	"name" : "bag of books",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 2,
	"uses": 5,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var bandages = { 
	"name" : "bandages",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["slow"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 5,
	"weight": 0,
	"uses": 3,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var dungeon_rations = { 
	"name" : "dungeon rations",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["ration"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 3,
	"weight": 1,
	"uses": 5,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var dwarven_hardtack = { 
	"name" : "dwarven hardtack",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["dwarf", "ration"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 3,
	"weight": 1,
	"uses": 7,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var elven_bread = { 
	"name" : "elven bread",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["ration"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 1,
	"uses": 7,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var halfling_pipeleaf = { 
	"name" : "halfling pipeleaf",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 5,
	"weight": 0,
	"uses": 6,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var healing_potion = { 
	"name" : "healing potion",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var keg_of_dwarven_stout = { 
	"name" : "keg of dwarven stout",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 4,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var personal_feast = { 
	"name" : "personal feast",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["ration"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 1,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var poultices_and_herbs = { 
	"name" : "poultices and herbs",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["slow"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 1,
	"uses": 2,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#---------Poisons----------------
var oil_of_tagit = { 
	"name" : "oil of tagit",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["dangerous", "applied"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": true,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 15,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var bloodweed = { 
	"name" : "bloodweed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["dangerous", "touch"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": true,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 12,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var goldenroot = { 
	"name" : "goldenroot",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["dangerous", "applied"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": true,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 20,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var serpents_tears = { 
	"name" : "serpents tears",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["dangerous", "touch"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": true,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 10,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#---------Gifts----------------
var peasant_gift = { 
	"name" : "peasant gift",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var fine_gift = { 
	"name" : "fine gift",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 55,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var noble_gift = { 
	"name" : "noble gift",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 200,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var gold_ring = { 
	"name" : "gold ring",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 75,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var finery = { 
	"name" : "finery",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 105,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var fine_tapestry = { 
	"name" : "fine tapestry",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 350, #TODO: plus a random amount
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var kings_crown = { 
	"name" : "kings crown",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": true,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 5000,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#--------- Transport ----------------
var cart_and_donkey = { 
	"name" : "cart and donkey",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50,
	"weight": -20,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var horse = { 
	"name" : "horse",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 75,
	"weight": -10,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var warhorse = { 
	"name" : "warhorse",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 400,
	"weight": -12,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var wagon = { 
	"name" : "wagon",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 150,
	"weight": -40,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var barge = { 
	"name" : "barge",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50,
	"weight": -15,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var river_boat = { 
	"name" : "river boat",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 150,
	"weight": -20,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var merchant_ship = { 
	"name" : "merchant ship",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 5_000,
	"weight": -200,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var war_ship = { 
	"name" : "war ship",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 20_000,
	"weight": -100,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#---------Property Deeds / Keys----------------
var hovel_deed = { 
	"name" : "hovel deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 20,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var cottage_deed = { 
	"name" : "cottage deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 500,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var house_deed = { 
	"name" : "house deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 2500,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var mansion_deed = { 
	"name" : "mansion deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 50_000,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var keep_deed = { 
	"name" : "keep deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 75_000,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var castle_deed = { 
	"name" : "castle deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 250_000,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
var grand_castle_deed = { 
	"name" : "grand castle deed",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": true,
	"is_magical": false,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 1_000_000,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#---------Magic Items----------------
#TODO: Finish
var argo_thaan_holy_avenger = { 
	"name" : "argo-thaan, holy avenger",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var arrows_of_acheron = { 
	"name" : "arrows of acheron",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var axe_of_the_conqueror_king = { 
	"name" : "axe of the conqueror-king",
	"weapon_tags": [],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var barb_of_the_black_gate = { 
	"name" : "barb of the black_gate",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var bag_of_holding = { 
	"name" : "bag of holding",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": true,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var burning_wheel = { 
	"name" : "burning wheel",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 2,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var captain_blighs_cornucopia = { 
	"name" : "captain bligh's cornucopia",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var carcosan_spire = { 
	"name" : "carcosan spire",
	"weapon_tags": ["thrown"],
	"range_tags": ["reach"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 3,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var cloak_of_silent_stars = { 
	"name" : "cloak of silent stars",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var coin_of_remembering = { 
	"name" : "coin of remembering",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var common_scroll = { 
	"name" : "common scroll",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var devilsbane_oil = { 
	"name" : "devilsbane oil",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var earworm_wax = { 
	"name" : "earworm wax",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_echo = { 
	"name" : "the echo",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_epoch_lens = { 
	"name" : "the epoch lens",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var farsight_stone = { 
	"name" : "farsight stone",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_fiasco_codex = { 
	"name" : "the fiasco codex",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var flask_of_breath = { 
	"name" : "flask of breath",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_wax_wings = { 
	"name" : "the wax wings",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var immovable_rod = { 
	"name" : "immovable rod",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var infinite_book = { 
	"name" : "infinite book",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var inspectacles = { 
	"name" : "inspectacles",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_kumeh_maneuver = { 
	"name" : "the ku'meh maneuver",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var lamented_memento = { 
	"name" : "lamented memento",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var lodestone_shield = { 
	"name" : "lodestone shield",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": ["+1 armor"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var map_of_the_last_patrol = { 
	"name" : "map of the last patrol",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var neds_head = { 
	"name" : "ned's head",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var nightsiders_key = { 
	"name" : "nightsider's key",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var sacred_herbs = { 
	"name" : "sacred herbs",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": 1,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_sartar_duck = { 
	"name" : "the sartar duck",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var tears_of_annalise = { 
	"name" : "tears of annalise",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var teleportation_room = { 
	"name" : "teleportation room",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": ["slow"],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var timunns_armor = { 
	"name" : "timunn's armor",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": ["1 armor"],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": true,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var titus_truthful_tallow = { 
	"name" : "titus truthful tallow",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var tricksy_rope = { 
	"name" : "tricksy rope",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var the_sterling_hand = { 
	"name" : "the sterling hand",
	"weapon_tags": [],
	"range_tags": ["near"],
	"general_tags": ["silver"], #TODO: implement silver tag
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 0,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var veliuss_gauntlets = { 
	"name" : "velius's gauntlets",
	"weapon_tags": [],
	"range_tags": [],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": false,
	"is_ranged": false,
	"is_melee": false,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 1,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var violation_glaive = { 
	"name" : "violation glaive",
	"weapon_tags": [],
	"range_tags": ["reach"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}
#TODO: Finish
var vorpal_sword = { 
	"name" : "vorpal sword",
	"weapon_tags": ["3 piercing"],
	"range_tags": ["close"],
	"general_tags": [],
	"armor_tags": [],
	"needs_repaired": false,
	"needs_reloaded": false,
	"is_weapon": true,
	"is_ranged": false,
	"is_melee": true,
	"is_armor": false,
	"is_gear": false,
	"is_poison": false,
	"is_gift": false,
	"is_certificate": false,
	"is_magical": true,
	"useful_info": "",
	"interesting_info": "",
	"coin" : 0,
	"weight": 2,
	"uses": null,
	"future_item_field_1": "",
	"future_item_field_2": "",
	"future_item_field_3": "",
	"future_item_field_4": "",
	"future_item_field_5": "",
}

#* ------------------ Disable or Enable ---------------------:

#* treasure drops:
var magical_items = [
	# bag_of_holding,
]
var minor_magical_items = [
	# common_scroll,
]
var holy_items = [
	# devilsbane_oil,
]
var planar_items = [
	# bag_of_holding
]
#* store items:
var ranged_weapons = [
	crossbow,
	fine_bow,
	hunters_bow,
	ragged_bow,
	bundle_of_arrows,
	elven_arrows,
]
var melee_weapons = [
	club,
	dagger,
	dueling_rapier,
	halberd,
	long_sword,
	battle_axe,
	flail,
	rapier,
	short_sword,
	axe,
	warhammer,
	mace,
	spear,
	staff,
	throwing_dagger,
]
var armor = [
	leather_armor,
	plate_armor,
	scale_mail,
	shield,
]
var gear = [
	adventuring_gear,
	antitoxin,
	bag_of_books,
	bandages,
	dungeon_rations,
	dwarven_hardtack,
	elven_bread,
	halfling_pipeleaf,
	healing_potion,
	keg_of_dwarven_stout,
	personal_feast,
	poultices_and_herbs,
]
var poisons = [
	oil_of_tagit,
	bloodweed,
	goldenroot,
	serpents_tears,
]
var gifts = [
	peasant_gift,
	fine_gift,
	noble_gift,
	gold_ring,
	finery,
	fine_tapestry,
	kings_crown,
]
var transport = [
	cart_and_donkey,
	horse,
	warhorse,
	wagon,
	barge,
	river_boat,
	merchant_ship,
	war_ship
]
var property_deeds = [
	hovel_deed,
	cottage_deed,
	house_deed,
	mansion_deed,
	keep_deed,
	castle_deed,
	grand_castle_deed,
]
var master_list = ranged_weapons + melee_weapons + armor + gear + poisons + gifts + transport + property_deeds

#* ------------------end of Disable/Enable ---------------------:

func generate_treasure(target):
	var modifier = 0
	modifier += target["attack_modifier"]
	var best_of_two = false
	var found_treasure = {
		"coins": 0,
		"special_items" : []
	}
	for tag in target["monster_tags"]:
		match tag:
			"hoarder": 
				best_of_two = true
			"far_from_home": 
				var rations = CharacterSheet.player_inventory["dungeon_rations"]
				rations.uses += 2
			"magical":
				print("player finds a magical item")
				found_treasure["special_items"].append(generate_special_item(magical_items))
			"divine" :
				print("player finds a holy item")
				found_treasure["special_items"].append(generate_special_item(holy_items))
			"planar" :
				print("player finds a planar item")
				found_treasure["special_items"].append(generate_special_item(planar_items))
			"lord_over_others":
				modifier += Utilities.roll_dice_for_total(1, 4)
			"ancient_and_noteworthy":
				modifier += Utilities.roll_dice_for_total(1, 4)
	var treasure = roll_for_treasure(best_of_two, target, modifier, found_treasure)
	print("treasure: %s" % treasure)
	return treasure



func roll_for_treasure(best_of_two, target, modifier, found_treasure):
	var roll = 0
	var treasure = found_treasure
	if best_of_two:
		roll = Utilities.best_dice(target["attack_number"], target["attack_base_damage"])
	else:
		roll = Utilities.roll_dice_for_total(target["attack_number"], target["attack_base_damage"])
	var treasure_rating = roll + modifier
	match treasure_rating:
		1: 
			# A few coins, 2d8 or so
			treasure["coins"] += Utilities.roll_dice_for_total(2, 8)
		2: 
			# An item useful to the current situation
			print("An item useful to the current situation")
			#TODO: FUTURE - make this more story based
			treasure["special_items"].append(healing_potion)
		3: 
			# Several coins, about 4d10
			treasure["coins"] +=  Utilities.roll_dice_for_total(4, 10)
		4:
			# A small item (gem, art) of considerable value, worth as much as
			# 2d10×10 coins, 0 weight
			treasure["coins"] +=  Utilities.roll_dice_for_total(2, 100)
		5:
			# Some minor magical trinket
			print("Some minor magical trinket")
			if minor_magical_items.size() > 0:
				treasure["special_items"].append(generate_special_item(minor_magical_items))
			else:
				print("roll again")
				return roll_for_treasure(best_of_two, target, modifier, found_treasure)
		6:
			# Useful information (in the form of clues, notes, etc.)
			print("Useful information (in the form of clues, notes, etc.)")
			treasure["special_items"].append(generate_special_item(CharacterSheet.current_location["useful_information"]))
		7:
			# A bag of coins, 1d4×100 or thereabouts. 1 weight per 100.
			treasure["coins"] +=  Utilities.roll_dice_for_total(1, 400)
		8:
			# A very valuable small item (gem, art) worth 2d6×100, 0 weight 
			treasure["coins"] +=  Utilities.roll_dice_for_total(2, 600)
		9:
			# 	A chest of coins and other small valuables. 1 weight but worth
			# 3d6×100 coins.
			treasure["coins"] +=  Utilities.roll_dice_for_total(3, 600)
		10:
			# A magical item or magical effect
			print("found a magical item or magical effect")
			if magical_items.size() > 0:
				treasure["special_items"].append(generate_special_item(magical_items))
			else:
				print("roll again")
				return roll_for_treasure(best_of_two, target, modifier, found_treasure)
		11:
			# Many bags of coins for a total of 2d4×100 or so
			treasure["coins"] +=  Utilities.roll_dice_for_total(2, 400)
		12:
			# A sign of office (crown, banner) worth at least 3d4×100 coins 
			treasure["coins"] +=  Utilities.roll_dice_for_total(3, 400)
		13:
			# A large art item worth 4d4×100 coins, 1 weight
			treasure["coins"] +=  Utilities.roll_dice_for_total(4, 400)
		14:
			# A unique item worth at least 5d4×100 coins
			treasure["coins"] +=  Utilities.roll_dice_for_total(5, 400)
		15:
			print("learning new spell")
			if "add_to_spellbook" in Moves.wizard_common_moves.keys():
				Moves.add_to_spellbook_fn()
			else:
				print("add_to_spellbook not enabled so roll again")
				return roll_for_treasure(best_of_two, target, modifier, found_treasure)
		16:
			#TODO: A portal or secret path (or directions to one) and roll again
			#TODO: give player an option to go in one-time portal like a enter_random_portal() in moves
			print("opening portal or secret path")
			# TODO: implement later
			# Locations.generate_random_portal()
			print("roll again")
			return roll_for_treasure(best_of_two, target, modifier, found_treasure)
		17:
			print("found a missing item if there is a missing item")	
			if CharacterSheet.missing_items.size() > 0:
				var missing_item = CharacterSheet.missing_items.duplicate(true).shuffle().pop_back()
				print("found missing item: %s" % missing_item)
				assert(missing_item != null)
				treasure["special_items"].append(CharacterSheet.missing_items.duplicate(true).shuffle().pop_back())
			else:
				print("roll again because there is no missing item")
				return roll_for_treasure(best_of_two, target, modifier, found_treasure)
		18:
			# A hoard: 1d10×1000 coins and 1d10×10 gems worth 2d6×100 each
			treasure["coins"] +=  Utilities.roll_dice_for_total(1, 100) * Utilities.roll_dice_for_total(2, 600)
	print("total treasure: %s" % treasure)
	return treasure

func generate_special_item(item_type):
	var potential_items = item_type.duplicate(true)
	var shuffled = potential_items.shuffle()
	assert(shuffled.size() > 0)
	return shuffled.pop_back()
